import { Inter } from "next/font/google";
import "./globals.css";
import UserID from "./auth_state_listener/page.js";
import { UserProvider } from "@/app/UserContext/page.js";
import Walkthrough from "@/Components/Walkthrough.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <UserProvider>
          
          {children}
        </UserProvider></body>
    </html>
  );
}
